### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by Pi1998** [evansnyamekye/Awesome-books-ES6#4]

**Comment by Pi1998** [comment]
# Optional Suggestion
- It would be better if you organized your color using `:root`  variables which offers flexibility in changing colors across your entire project.

🔧 For instance, you can define colors like:
`root:{
   --primary-color: #36b37e;
   --secondary-color: #fff;
}`

📝 This approach also keeps your styles clean and makes it easier to adjust colors in the future.
- Apart from that, your project looks amazing, `Congratulations! 💯 `

**Comment by evansnyamekye** [comment]
### Hi @Pi1998 👍, 

I am grateful for the review, as stated I will make all changes suggested in your review. I believe this will let grow and learn new things a s a developer. 

Thank you 🛩️.
