### ISSUE TITLE
Call function Inside DOMContentLoaded Event Listener

### ISSUE THREAD

**Issue by Titus-Kiplagat** [evansnyamekye/Awesome-books-ES6#5]
###### Issue description;
It is recommended to call a `pages.displayListPage` function inside a `DOMContentLoaded` event listener to ensure that it executes after the DOM has fully loaded. This enhancement proposal aims to improve the reliability and maintainability of the code.

**Comment by evansnyamekye** [comment]
### Hi @Titus-Kiplagat 👍 

Changes recommended is well noted. I will modify the functionality by calling the pages.displayListPage inside the DomContent as  suggested. 

Thank you 😃.
